### ISSUE TITLE
building

### ISSUE THREAD

**Issue by SohrabIranpak** [tytydraco/Ludere#10]
Invalid injected android support version '202.7660.26.42.7486908', expected to be of the form 'w.x.y.z'

**Comment by tytydraco** [comment]
Try using Android Studio Canary

**Comment by SohrabIranpak** [comment]
Execution failed for task ':app:lintVitalAnalyzeRelease'.
> Could not resolve all files for configuration ':app:lintClassPath'.
   > Could not find lint-checks-30.0.0-alpha15.jar (com.android.tools.lint:lint-checks:30.0.0-alpha15).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-checks/30.0.0-alpha15/lint-checks-30.0.0-alpha15.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by SohrabIranpak** [comment]
i can download it from browser 
but bulid goes wtih error

**Comment by tytydraco** [comment]
Not sure, this seems like an Android Studio build error, not part of the app

**Comment by SohrabIranpak** [comment]
changed :
classpath 'com.android.tools.build:gradle:7.0.0-alpha15'    ->   in build.gradle
to:
classpath 'com.android.tools.build:gradle:7.0.0-alpha12'

solved and error is gone
thanks a lot for your hard work
it's a great tool
