### ISSUE TITLE
workflow does not work any more!!

### ISSUE THREAD

**Issue by SohrabIranpak** [tytydraco/Ludere#15]
hi just checked now
workflow won't run

**Comment by tytydraco** [comment]
Thanks for the report, I'll look into it

**Comment by SohrabIranpak** [comment]
it was okey yesterday
i don't know it may be a github issue

**Comment by tytydraco** [comment]
> it was okey yesterday
> i don't know it may be a github issue

Fixed! Re-clone the repo and try again <3
