### ISSUE TITLE
Is it possible to have the lower screen of the Nintendo ds respond to touch.

### ISSUE THREAD

**Issue by MrThista** [tytydraco/Ludere#4]

**Comment by tytydraco** [comment]
Have you enabled the touch mode variable for the ds core? The default is pointer mode.

**Comment by MrThista** [comment]
I have not! I will make a point of reading all core notes before posting again. I will post again once I have tested.

**Comment by MrThista** [comment]
Confirmed working when enabling desmume_pointer_type=touch on DeSmuME2015
