### ISSUE TITLE
Question.. PSX Multi Disc

### ISSUE THREAD

**Issue by njpontes1** [tytydraco/Ludere#5]
Im really excited with your work! Really great work with this Simpliest Emulator!! :D

But I have a question.. how can I make Multi-disc PSX games playable trough this method?

Best regards!

**Comment by tytydraco** [comment]
Hmmm, I know that the LibretroDroid API supports multiple disks, I just need to add support. Let me look into it and I'll get back to you :)

**Comment by njpontes1** [comment]
Omg Thank you so Much 👍

**Comment by tytydraco** [comment]
Hey @njpontes1, I just pushed a few changes that should make it compatible with multiple discs. I'd appreciate it if you could try them for me. You can access the new overlay menu by pressing the back button on your device. Let me know if disc-switching works as expected.

**Comment by njpontes1** [comment]
It booted up with the PBP file :D now i need to reach the swap disc part of the game to be sure, but so far so good

**Comment by tytydraco** [comment]
Awesome, thanks in advance 👍

**Comment by tytydraco** [comment]
@njpontes1 Wanted to follow up. Did disc switching work as intended?
