### ISSUE TITLE
PCSX Core , Analog Mode not recognized on games 

### ISSUE THREAD

**Issue by njpontes1** [tytydraco/Ludere#6]
Hey! I can't use the Analog Type to some games, like Ape Escape or Chrono Cross, they dont recognize as being in Analog Mode.

Tried this core variable:

<string name="config_variables">pcsx_rearmed_pad1type = "analog", pcsx_rearmed_pad2type = "standard"</string>

**Comment by tytydraco** [comment]
You need to use the exact format of key=value, so:

pcsx_rearmed_pad1type=analog
